version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: plataforma_maternidade_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plataforma_maternidade
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: .
    container_name: plataforma_maternidade_web
    restart: always
    ports:
      - "8080:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: php -S 0.0.0.0:8000 -t /var/www/html

volumes:
  mysql_data: 